<?php 
define('DRQ_PREG_MOTHER_DATA_VERSION', '1.0');
define('DRQ_PREG_MOTHER_DATA_FOLDER', 'drq_preg_mother_data');
define('DRQ_PREG_MOTHER_DATA_PATH', MODULES_PATH.DRQ_PREG_MOTHER_DATA_FOLDER.'/');
