<?php 
define('DRQ_INFORMATION_CHILD_VERSION', '1.0');
define('DRQ_INFORMATION_CHILD_FOLDER', 'drq_information_child');
define('DRQ_INFORMATION_CHILD_PATH', MODULES_PATH.DRQ_INFORMATION_CHILD_FOLDER.'/');
