
CREATE TABLE IF NOT EXISTS `drq_birth_death_info` (
  `drq_birth_death_info_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `birth_reason` varchar(50) DEFAULT NULL,
  `anc_1` varchar(50) DEFAULT NULL,
  `anc_2` varchar(30) DEFAULT NULL,
  `anc_3` varchar(30) DEFAULT NULL,
  `services_received` varchar(30) DEFAULT NULL,
  `treatment_visit` varchar(30) DEFAULT NULL,
  `advice_recieved` varchar(30) DEFAULT NULL,
  `pregnancy_period` varchar(50) DEFAULT NULL,
  `delivery_place` varchar(50) DEFAULT NULL,
  `delivered_home_assisted` varchar(50) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_birth_death_info_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `drq_father_data` (
  `drq_father_data` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `fatherstatus` varchar(50) NOT NULL,
  `fathername` varchar(50) NOT NULL,
  `fatherdob` varchar(30) DEFAULT NULL,
  `childage` varchar(30) NOT NULL,
  `mrgage` varchar(30) DEFAULT NULL,
  `dateofdeath` varchar(50) NOT NULL,
  `registrationdate` varchar(50) DEFAULT NULL,
  `deathreason` varchar(30) DEFAULT NULL,
  `merragedate` varchar(30) DEFAULT NULL,
  `hospitalvisited` varchar(30) DEFAULT NULL,
  `reasonforvisit` varchar(50) DEFAULT NULL,
  `sfatheroccupation` varchar(50) DEFAULT NULL,
  `fathereducation` varchar(30) DEFAULT NULL,
  `fathereincome` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_father_data`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `drq_general_info` (
  `drq_general_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `death_reason` varchar(50) NOT NULL,
  `dob` varchar(50) NOT NULL,
  `dod` varchar(30) DEFAULT NULL,
  `periodfordeath` varchar(30) NOT NULL,
  `deathreg` varchar(30) DEFAULT NULL,
  `gender` varchar(50) NOT NULL,
  `mothercarrying` varchar(50) DEFAULT NULL,
  `anc2` varchar(30) DEFAULT NULL,
  `anc3` varchar(30) DEFAULT NULL,
  `services` varchar(30) DEFAULT NULL,
  `visitinghospital` varchar(50) DEFAULT NULL,
  `pregnecyperiod` varchar(50) DEFAULT NULL,
  `deleveryplace` varchar(30) DEFAULT NULL,
  `childedustatus` varchar(30) DEFAULT NULL,
  `birthorder` varchar(30) DEFAULT NULL,
  `immudeath` varchar(50) DEFAULT NULL,
  `anc1` varchar(50) DEFAULT NULL,
  `treatmentstatus3` varchar(30) DEFAULT NULL,
  `deleveryassist` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_general_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `drq_immunization` (
  `drq_immunization_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `bcgandopv` varchar(50) NOT NULL,
  `hpatities1` varchar(50) DEFAULT NULL,
  `dptandopv` varchar(30) DEFAULT NULL,
  `hpatities2` varchar(30) DEFAULT NULL,
  `dpv2andopv3` varchar(30) DEFAULT NULL,
  `dpv3andopv4` varchar(30) DEFAULT NULL,
  `hepatitiesB3` varchar(30) DEFAULT NULL,
  `measlesandopv5` varchar(50) NOT NULL,
  `mmr` varchar(50) DEFAULT NULL,
  `booster1` varchar(30) DEFAULT NULL,
  `typhoid` varchar(30) DEFAULT NULL,
  `booster2` varchar(30) DEFAULT NULL,
  `tetanustoxid1` varchar(30) DEFAULT NULL,
  `tetanustoxide2` varchar(30) DEFAULT NULL,
  `hib1` varchar(100) DEFAULT NULL,
  `hib2` varchar(30) DEFAULT NULL,
  `hib3` varchar(30) DEFAULT NULL,
  `hibbooster` varchar(30) DEFAULT NULL,
  `hepa1` varchar(30) DEFAULT NULL,
  `hepa2` varchar(30) DEFAULT NULL,
  `vita` varchar(30) DEFAULT NULL,
  `chicknpox` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_immunization_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `drq_mother_data` (
  `drq_mother_data` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `mother_name` varchar(50) NOT NULL,
  `mother_dob` varchar(30) DEFAULT NULL,
  `motherdeathstatus` varchar(30) NOT NULL,
  `periodofdeath` varchar(30) DEFAULT NULL,
  `services_recieved` varchar(50) NOT NULL,
  `pregnancyperiod` varchar(50) DEFAULT NULL,
  `deliveryplace` varchar(30) DEFAULT NULL,
  `deliveryassistby` varchar(30) DEFAULT NULL,
  `hospitaldistance` varchar(30) DEFAULT NULL,
  `hospitaltype` varchar(50) DEFAULT NULL,
  `amountpaid` varchar(50) DEFAULT NULL,
  `hospital_reason_anc1` varchar(30) DEFAULT NULL,
  `hospital_reason_anc2` varchar(30) DEFAULT NULL,
  `hospital_reason_anc3` varchar(30) DEFAULT NULL,
  `deliverytype` varchar(50) DEFAULT NULL,
  `deliveryexplanation` varchar(50) DEFAULT NULL,
  `birthchild` varchar(30) DEFAULT NULL,
  `hospitalvisited` varchar(30) DEFAULT NULL,
  `datevisitedhospital` varchar(30) DEFAULT NULL,
  `mrgdate` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_mother_data`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `drq_normal_mother_data` (
  `drq_normal_mother_data` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `mothername` varchar(50) NOT NULL,
  `motherdob` varchar(50) NOT NULL,
  `hospitalreason` varchar(30) DEFAULT NULL,
  `mothereducation` varchar(30) NOT NULL,
  `motherage` varchar(30) DEFAULT NULL,
  `motherdeathage` varchar(50) NOT NULL,
  `deathregistration` varchar(50) DEFAULT NULL,
  `ration_status` varchar(30) DEFAULT NULL,
  `mothermrgage` varchar(30) DEFAULT NULL,
  `txtmotheroccu` varchar(30) DEFAULT NULL,
  `txtmotherdeathrsn` varchar(50) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_normal_mother_data`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `drq_summary` (
  `drq_summary_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `door_num` varchar(50) NOT NULL,
  `sdate` varchar(50) NOT NULL,
  `village` varchar(30) NOT NULL,
  `grama` varchar(30) NOT NULL,
  `taluk` varchar(30) NOT NULL,
  `district` varchar(30) NOT NULL,
  `divison` varchar(30) DEFAULT NULL,
  `headname` varchar(50) NOT NULL,
  `enumerator` varchar(50) DEFAULT NULL,
  `respondant` varchar(50) DEFAULT NULL,
  `father_death` varchar(50) DEFAULT NULL,
  `relationship` varchar(50) DEFAULT NULL,
  `child_death` varchar(50) DEFAULT NULL,
  `num_child_death` varchar(50) DEFAULT NULL,
  `num_pre_birth` varchar(50) DEFAULT NULL,
  `num_post_birth` varchar(50) DEFAULT NULL,
  `mother_death` varchar(20) DEFAULT NULL,
  `pregnancy_period` varchar(50) DEFAULT NULL,
  `general` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`drq_summary_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `household_entry` (
  `household_entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `entry_village_name` varchar(255) NOT NULL,
  `entry_grama_panchayat` varchar(255) NOT NULL,
  `entry_door_no` int(11) NOT NULL,
  `entry_date_today` date NOT NULL,
  `entry_taluk_block` varchar(255) NOT NULL,
  `entry_district_name` varchar(255) NOT NULL,
  `entry_name_head_of_fly` varchar(255) NOT NULL,
  `entry_division` varchar(50) NOT NULL,
  `entry_name_of_resp` varchar(255) NOT NULL,
  `entry_name_of_enum` varchar(255) NOT NULL,
  `entry_rel_wid_child` varchar(255) NOT NULL,
  `entry_tot_no_ppl` int(11) NOT NULL,
  `entry_no_of_male_ppl` int(11) NOT NULL,
  `entry_no_of_female_ppl` int(11) NOT NULL,
  `entry_type_of_rationcrd` varchar(100) NOT NULL,
  `entry_tot_no_childrns` int(11) NOT NULL,
  `entry_age0_3yrsmale` int(11) NOT NULL,
  `entry_age3_6yrsmale` int(11) NOT NULL,
  `entry_age6_14yrsmale` int(11) NOT NULL,
  `entry_age14_18yrsmale` int(11) NOT NULL,
  `entry_age0_3yrsfemale` int(11) DEFAULT NULL,
  `entry_age3_6yrsfemale` int(11) DEFAULT NULL,
  `entry_age6_14yrsfemale` int(11) DEFAULT NULL,
  `entry_age14_18yrsfemale` int(11) DEFAULT NULL,
  `entry_no_of_male_chld` int(11) NOT NULL,
  `entry_no_of_female_chld` int(11) NOT NULL,
  `entry_no_orp_semi` int(11) NOT NULL,
  `entry_no_child_disability_male` int(11) DEFAULT NULL,
  `entry_no_of_male_orpdis` int(11) DEFAULT NULL,
  `entry_no_child_disability_female` int(11) DEFAULT NULL,
  `entry_no_of_female_orpdis` int(11) DEFAULT NULL,
  `entry_child_death` varchar(255) DEFAULT NULL,
  `entry_mother_death` varchar(255) DEFAULT NULL,
  `entry_father_death` varchar(255) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`household_entry_id`),
  UNIQUE KEY `household_voters_id` (`household_voters_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `household_survey_list` (
  `household_survey_list_id` int(11) NOT NULL AUTO_INCREMENT,
  `ref_id` int(11) NOT NULL,
  `list_id` int(11) NOT NULL,
  `survey_name_survey` varchar(255) DEFAULT NULL,
  `survey_age_survey` int(11) DEFAULT NULL,
  `survey_gender_survey` varchar(10) DEFAULT NULL,
  `survey_relationship_with_head_family` varchar(255) DEFAULT NULL,
  `survey_mother_child_relationship_survey` varchar(255) DEFAULT NULL,
  `survey_father_child_relationship_survey` varchar(255) DEFAULT NULL,
  `survey_guardian_child_relationship_survey` varchar(255) DEFAULT NULL,
  `survey_alive_dead_survey` varchar(255) DEFAULT NULL,
  `survey_education_survey` varchar(255) DEFAULT NULL,
  `survey_occupation_survey` varchar(255) DEFAULT NULL,
  `survey_annual_income_survey` varchar(255) DEFAULT NULL,
  `survey_marital_status_survey` varchar(255) DEFAULT NULL,
  `survey_married_age_survey` int(11) DEFAULT NULL,
  PRIMARY KEY (`household_survey_list_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `household_survey_main` (
  `household_survey_main_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `survey_name_of_head_family` varchar(255) DEFAULT NULL,
  `survey_address_of_head_family` varchar(255) NOT NULL,
  `survey_religion_survey` varchar(255) NOT NULL,
  `survey_caste_survey` varchar(255) NOT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`household_survey_main_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `house_dropdwn` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `villages` varchar(255) NOT NULL,
  `grama_panchayat` varchar(255) NOT NULL,
  `division` varchar(255) NOT NULL,
  `district` varchar(255) NOT NULL,
  `states` varchar(255) NOT NULL,
  `taluk` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_birth_details` (
  `ocop_birth_details_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `birth_weight` varchar(50) NOT NULL,
  `birth_disability` varchar(50) DEFAULT NULL,
  `birth_registration` varchar(30) NOT NULL,
  `birth_certificate` varchar(30) NOT NULL,
  `birth_not_registered` varchar(30) NOT NULL,
  `nutricious_received` varchar(30) NOT NULL,
  `pregnancy_period` varchar(30) DEFAULT NULL,
  `delivery_place` varchar(50) NOT NULL,
  `delivery_assisted` varchar(50) NOT NULL,
  `hospital_distance` varchar(50) NOT NULL,
  `hospital_type` varchar(50) NOT NULL,
  `delivery_paid` varchar(50) NOT NULL,
  `delivery_type` varchar(50) NOT NULL,
  `delivery_difficult` varchar(50) DEFAULT NULL,
  `delivery_number` varchar(50) NOT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_birth_details_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_current_details` (
  `ocop_current_details_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `child_weight` varchar(50) NOT NULL,
  `child_height` varchar(50) DEFAULT NULL,
  `child_disability` varchar(30) NOT NULL,
  `child_problem` varchar(30) NOT NULL,
  `assistance_recieved` varchar(30) NOT NULL,
  `assistance_given` varchar(30) NOT NULL,
  `health_center` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_current_details_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_education` (
  `ocop_education_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `enrollment_school` varchar(50) NOT NULL,
  `present_class` varchar(50) DEFAULT NULL,
  `enrollment_pre_primary` varchar(30) DEFAULT NULL,
  `pre_primary_type` varchar(30) DEFAULT NULL,
  `pre_primary_date` varchar(30) DEFAULT NULL,
  `enrollment_primary` varchar(30) DEFAULT NULL,
  `primary_type` varchar(30) DEFAULT NULL,
  `primary_date` varchar(50) NOT NULL,
  `present_school` varchar(50) DEFAULT NULL,
  `attending_regularly` varchar(30) DEFAULT NULL,
  `mismatch_reason` varchar(30) DEFAULT NULL,
  `non_enrollment_reasons` varchar(30) DEFAULT NULL,
  `drop_out_reason` varchar(30) DEFAULT NULL,
  `re_enrolment_attempts` varchar(30) DEFAULT NULL,
  `failure_attempts_reasons` varchar(100) DEFAULT NULL,
  `disabled_facilities` varchar(30) DEFAULT NULL,
  `special_school` varchar(30) DEFAULT NULL,
  `transport_mode` varchar(30) DEFAULT NULL,
  `distance_traveled` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_education_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_father_data` (
  `ocop_father_data_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `fatherstatus` varchar(50) NOT NULL,
  `fathername` varchar(50) NOT NULL,
  `fatherdob` varchar(30) DEFAULT NULL,
  `fatherpreaddr` varchar(30) NOT NULL,
  `fatherperaddr` varchar(30) DEFAULT NULL,
  `fatherreligion` varchar(50) NOT NULL,
  `fathercaste` varchar(50) DEFAULT NULL,
  `fatherration` varchar(30) DEFAULT NULL,
  `fatherrationtype` varchar(30) DEFAULT NULL,
  `fathermrg` varchar(30) DEFAULT NULL,
  `fathermrgage` varchar(50) DEFAULT NULL,
  `fatherhosvisited` varchar(50) DEFAULT NULL,
  `fatherhosdate` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_father_data_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_general_info` (
  `ocop_general_info_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `child_name` varchar(100) NOT NULL,
  `dob` varchar(50) NOT NULL,
  `gender` varchar(30) NOT NULL,
  `father_name` varchar(30) NOT NULL,
  `mother_name` varchar(30) NOT NULL,
  `present_addr` varchar(500) NOT NULL,
  `permanent_addr` varchar(500) DEFAULT NULL,
  `child_living` varchar(50) NOT NULL,
  `child_orphan` varchar(50) NOT NULL,
  `child_orphan_yes` varchar(50) DEFAULT NULL,
  `child_orphan_since` varchar(50) DEFAULT NULL,
  `adopted_child` varchar(50) DEFAULT NULL,
  `religion` varchar(50) NOT NULL,
  `caste` varchar(50) NOT NULL,
  `ration_card_name` varchar(50) DEFAULT NULL,
  `ration_card_type` varchar(50) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_general_info_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_guardian_data` (
  `ocop_guardian_data_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `guardian_status` varchar(50) NOT NULL,
  `guardian_name` varchar(50) NOT NULL,
  `guardian_dob` varchar(30) DEFAULT NULL,
  `guardian_preaddr` varchar(30) NOT NULL,
  `guardian_peraddr` varchar(30) DEFAULT NULL,
  `guardian_religion` varchar(50) NOT NULL,
  `guardian_caste` varchar(50) DEFAULT NULL,
  `guardian_ration` varchar(30) DEFAULT NULL,
  `guardian_rationtype` varchar(30) DEFAULT NULL,
  `guardian_mrg` varchar(30) DEFAULT NULL,
  `guardian_mrgage` varchar(50) DEFAULT NULL,
  `guardian_hosvisited` varchar(50) DEFAULT NULL,
  `guardian_hosdate` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_guardian_data_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_immunization` (
  `ocop_immunization_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `bcgandopv` varchar(50) NOT NULL,
  `hpatities1` varchar(50) DEFAULT NULL,
  `dptandopv` varchar(30) DEFAULT NULL,
  `hpatities2` varchar(30) DEFAULT NULL,
  `dpv2andopv3` varchar(30) DEFAULT NULL,
  `dpv3andopv4` varchar(30) DEFAULT NULL,
  `hepatitiesB3` varchar(30) DEFAULT NULL,
  `measlesandopv5` varchar(50) NOT NULL,
  `mmr` varchar(50) DEFAULT NULL,
  `booster1` varchar(30) DEFAULT NULL,
  `typhoid` varchar(30) DEFAULT NULL,
  `booster2` varchar(30) DEFAULT NULL,
  `tetanustoxid1` varchar(30) DEFAULT NULL,
  `tetanustoxide2` varchar(30) DEFAULT NULL,
  `hib1` varchar(100) DEFAULT NULL,
  `hib2` varchar(30) DEFAULT NULL,
  `hib3` varchar(30) DEFAULT NULL,
  `hibbooster` varchar(30) DEFAULT NULL,
  `hepa1` varchar(30) DEFAULT NULL,
  `hepa2` varchar(30) DEFAULT NULL,
  `vita` varchar(30) DEFAULT NULL,
  `chicknpox` varchar(30) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_immunization_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_mother_data` (
  `ocop_mother_data_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `mother_status` varchar(50) NOT NULL,
  `mother_name` varchar(50) NOT NULL,
  `mother_dob` varchar(50) DEFAULT NULL,
  `present_address` varchar(100) NOT NULL,
  `permanent_address` varchar(100) DEFAULT NULL,
  `mother_religion` varchar(50) NOT NULL,
  `mother_caste` varchar(50) DEFAULT NULL,
  `ration_status` varchar(30) DEFAULT NULL,
  `ration_type` varchar(30) DEFAULT NULL,
  `marriage_date` varchar(50) DEFAULT NULL,
  `marriage_age` varchar(50) DEFAULT NULL,
  `hospital_visited` varchar(50) DEFAULT NULL,
  `hospital_reason` varchar(50) DEFAULT NULL,
  `hospital_reason_anc1` varchar(30) DEFAULT NULL,
  `hospital_reason_anc2` varchar(30) DEFAULT NULL,
  `hospital_reason_anc3` varchar(30) DEFAULT NULL,
  `madilu_scheme` varchar(50) DEFAULT NULL,
  `taayi_scheme` varchar(50) DEFAULT NULL,
  `janani_scheme` varchar(30) DEFAULT NULL,
  `services_recieved` varchar(50) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_mother_data_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_protection` (
  `ocop_protection_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `child_working` varchar(50) NOT NULL,
  `working_status` varchar(50) DEFAULT NULL,
  `work_type` varchar(30) DEFAULT NULL,
  `whom_work` varchar(30) DEFAULT NULL,
  `missing` varchar(30) DEFAULT NULL,
  `missing_reason` varchar(30) DEFAULT NULL,
  `missing_date` varchar(30) DEFAULT NULL,
  `fir_registered` varchar(100) DEFAULT NULL,
  `fir_date` varchar(50) DEFAULT NULL,
  `child_return` varchar(100) DEFAULT NULL,
  `return_date` varchar(50) DEFAULT NULL,
  `child_marriage` varchar(100) DEFAULT NULL,
  `marriage_date` varchar(50) DEFAULT NULL,
  `minor_pregnancy` varchar(50) DEFAULT NULL,
  `devadasi_mother` varchar(50) DEFAULT NULL,
  `devadasi_system` varchar(50) DEFAULT NULL,
  `devadasi_reason` varchar(150) DEFAULT NULL,
  `child_rescued` varchar(100) DEFAULT NULL,
  `before_cwc` varchar(100) DEFAULT NULL,
  `service_kind` varchar(100) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_protection_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_summary` (
  `ocop_summary_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `door_num` varchar(50) NOT NULL,
  `sdate` varchar(50) NOT NULL,
  `village` varchar(30) NOT NULL,
  `grama` varchar(30) NOT NULL,
  `taluk` varchar(30) NOT NULL,
  `district` varchar(30) NOT NULL,
  `divison` varchar(30) DEFAULT NULL,
  `headname` varchar(50) NOT NULL,
  `enumerator` varchar(50) NOT NULL,
  `respondant` varchar(50) NOT NULL,
  `guardian` varchar(50) NOT NULL,
  `relationship` varchar(50) NOT NULL,
  `mother_name` varchar(50) NOT NULL,
  `father_name` varchar(50) NOT NULL,
  `child_name` varchar(50) NOT NULL,
  `age` varchar(50) NOT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `present_class` varchar(50) DEFAULT NULL,
  `orphan` varchar(30) DEFAULT NULL,
  `disability_type` varchar(75) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_summary_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ocop_welfare` (
  `ocop_welfare_id` int(11) NOT NULL AUTO_INCREMENT,
  `household_voters_id` varchar(255) NOT NULL,
  `summary_id` int(11) NOT NULL,
  `bhagyalaxmi_scheme` varchar(50) DEFAULT NULL,
  `bicycle_scheme` varchar(50) DEFAULT NULL,
  `devadasi_scheme` varchar(50) DEFAULT NULL,
  `disability_certificate` varchar(50) DEFAULT NULL,
  `facilities_provided` varchar(150) DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ocop_welfare_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
