<?php 
define('DRQ_BIRTH_DEATH_INFO_VERSION', '1.0');
define('DRQ_BIRTH_DEATH_INFO_FOLDER', 'drq_birth_death_info');
define('DRQ_BIRTH_DEATH_INFO_PATH', MODULES_PATH.DRQ_BIRTH_DEATH_INFO_FOLDER.'/');
